// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njzchfztfxeoofamzulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qemNoZnp0Znhlb29mYW16dWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTMxMDMsImV4cCI6MjA2MjE4OTEwM30.pq-b36NfIYoL4F7pKd6Xh2uZyY0LgMhn5rkylrD7pPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);